name: deploy on main

on:
  push:
    branches:
      - main
      - dist

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_EMAIL_SERVICE_ID: ${{ vars.VITE_EMAIL_SERVICE_ID }}
          VITE_EMAIL_TEMPLATE_ID: ${{vars.VITE_EMAIL_TEMPLATE_ID}}
          VITE_EMAIL_USER_ID: ${{vars.VITE_EMAIL_USER_ID}}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: dist
          clean: true
          single-commit: true
